server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# Spring 설정
spring:
  logging:
    level:
      root: INFO
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations:
        - classpath:schema-psql.sql

  jpa:
    hibernate:
      ddl-auto: update # create   # DDL? schema-psql.sql ? ??
    show-sql: false
    properties:
      hibernate.default_schema: discodeit
      hibernate:
        format_sql: true
        use_sql_comments: false

# 파일 업로드 관련 사용자 정의 설정
file:
  upload:
    # OS별 외부 파일 저장 경로 설정
    all:
      # 윈도우 OS용 파일 업로드 기본 경로
      path: ./files


management:
  endpoints:
    health:
      show-details: never
    info:
      env:
        enabled: false

  info:
    env:
      enabled: true             # 환경 변수 정보 포함
    java:
      enabled: true             # Java 정보 포함
    os:
      enabled: true             # OS 정보 포함
  prometheus:
    metrics:
      export:
        enabled: true  # 프로메테우스 메트릭 활성화
  metrics:
    tags:
      application: library-system  # 메트릭 태그 추가
